spring:
  application:
    name: turbin
    
server:
  port: 5001
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
      
turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")