spring:
  application:
    name: config-server
    
    
  profiles:
    active: native
  
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

        git:
          uri: https://github.com/zhangguo123/kelaode
          searchPaths: sp-config
          username: zhangguo123
          password: 18335869563zh
        
    
  host: 192.168.67.130
  port: 5672
  username: admin
  password: admin

    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh