spring:
  application:
    name: config-server
    
    
 # profiles:
 #   active: native
  
  cloud:
    config:
      server:
 #       native:
 #         search-locations: classpath:/config

<<<<<<< master
        git:
          uri: https://zhangguo123/sp-config
=======
#        git:
#          uri: https://github.com/你的用户路径/sp-config
>>>>>>> 0419b1b 更改配置
#          searchPaths: config
#          username: your-username
#          password: your-password
        
    
  rabbitmq:
<<<<<<< master
    host: 192.168.67.130
=======
    host: 192.168.64.140
>>>>>>> 0419b1b 更改配置
    port: 5672
    username: admin
    password: admin

    
server:
  port: 6001
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh